### ISSUE TITLE
Installation Failure for megatron-core==0.4.0 due to Missing requirements.txt

### ISSUE THREAD

**Issue by chaitanya-gvs** [AI4Bharat/indic-asr-api-backend#3]
#### Issue Summary:
While installing `nemo_toolkit==1.23.0rc0`, the installation of `megatron-core==0.4.0` dependency fails due to a `FileNotFoundError` for `megatron/core/requirements.txt`.

#### Steps to Reproduce:
1. Run a script (reinstall.sh) that attempts to install `nemo_toolkit==1.23.0rc0`.
2. The installation process starts normally, installing/updating various packages.
3. Upon reaching `megatron-core==0.4.0`, the installation fails.

#### Expected Behavior:
The `megatron-core` package should install without errors.

#### Actual Behavior:
The installation process fails with the following error message:
```
Collecting megatron-core==0.4.0 (from nemo_toolkit==1.23.0rc0)
  Using cached megatron_core-0.4.0.tar.gz (154 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/centos/miniconda3/envs/ai4b_asr/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/centos/miniconda3/envs/ai4b_asr/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/centos/miniconda3/envs/ai4b_asr/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-9fq_ra8j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-9fq_ra8j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-9fq_ra8j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-9fq_ra8j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
        File "<string>", line 45, in req_file
      FileNotFoundError: [Errno 2] No such file or directory: 'megatron/core/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

This error is triggered during the step of "Getting requirements to build wheel" for the `megatron-core` package.

#### Environment:
- OS: centOS
- Python version: 3.8
- Conda environment

#### Additional Context:
The issue seems to be related to a missing `requirements.txt` file in the `megatron-core` package. This error might indicate an issue with the package structure or setup script of `megatron-core`.

#### Possible Solutions:
- Verification of the `megatron-core` package contents to ensure `requirements.txt` is correctly included.
- Review and update the installation script if necessary.

I am seeking assistance in resolving this issue to successfully install `nemo_toolkit==1.23.0rc0`.

Thank you for your attention to this matter.

**Comment by munendra7777** [comment]
I am facing the same issue.
